# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 mord58562
# This file is part of TheAnkiDote. See LICENSE for details.
"""Structured replacements for condition summaries.

The base summaries in `_conditions.py` are not thin - median 800
characters - but they are unstructured: one dense block with section
labels used inconsistently, which is exactly what makes a long popup
unreadable. The information is there and none of it is findable.

This file holds rewritten versions keyed by canonical name, merged over
the base at import. An override layer rather than edits in place,
because:

  * `_conditions.py` is a 2,589-entry generated-looking file, and
    hand-editing entries scattered through it is how you lose them;
  * progress is trackable - `len(RICH_SUMMARIES)` is the count of
    conditions upgraded so far, and the test suite can assert every
    override targets a real entry;
  * a bad override is one dict key to delete, not a diff to unpick.

House style, matching the scaffold used on the cards these popups sit
beside: a one-line lede defining the condition, then `Label:` sections
in the order Epidemiology, Causes, Pathophysiology, Clinical features,
Investigations, Differential, Management - including only the sections
that earn their place. `Note:` carries the single most discriminating
fact, and `Red flags:` anything time-critical.

**Length is governed by bullet count, not characters.** Measured across
the shipped library, the overrides that fit the 620px popup carry a
median of 4 bulleted points and the ones that scroll carry 10 - at an
identical median length of about 1,000 characters. Character count does
not discriminate between the two, which is why the previous rule here
(cap 1,200, aim for 1,050) produced entries that were the right length
and scrolled anyway: 30 of the first 55 were over the cap.

The working budget is five or six sections, and few *bulleted* points. A
section bullets when it splits into four or more points with at least
one of them substantial - `_worthBulleting` in web/marker.js - so a run
of short items is both cheaper and more readable set as prose. Check
against `PopupHeightBudget` in tests/test_vocab.py, which estimates
rendered height directly; a character count tells you nothing.

Australian guidance first (eTG, AMH, PBS, RANZCP), and where a popup
would otherwise imply a US pathway the entry says what is done here.
"""

# Conditions the base database never listed. Kept here beside their
# summaries rather than appended to `_conditions.py`, so the whole of a
# new entry - name, aliases, article link and text - lives in one place.
# `summary` is filled from RICH_SUMMARIES below at import.
# No `nbk` accession here on purpose. An NBK id has to be verified
# against the actual article - a plausible-looking one that belongs to
# something else is worse than none, because it opens the wrong page
# confidently. Three invented ids made it into preview 8 before this
# was caught: NBK519494, used for febrile neutropenia, is in fact
# "Anatomy, Bony Pelvis and Lower Limb, Knee Lateral Meniscus". Without
# an accession these fall back to a StatPearls in-book search, which now
# uses US spelling and finds the article.
NEW_CONDITIONS = [
    {
        "name": "Febrile neutropenia",
        "aliases": ["Neutropenic fever", "Neutropenic sepsis"],
        "utd": [["Overview", "overview of neutropenic fever syndromes"]],
        "summary": "",
    },
    {
        "name": "Syndrome of inappropriate antidiuretic hormone secretion",
        "aliases": ["SIADH", "Inappropriate ADH secretion",
                    "Syndrome of inappropriate ADH"],
        "utd": [["Overview", "pathophysiology and etiology of the syndrome "
                             "of inappropriate antidiuretic hormone secretion"]],
        "summary": "",
    },
    {
        "name": "Tumour lysis syndrome",
        "aliases": ["Tumor lysis syndrome", "TLS"],
        "utd": [["Overview", "tumor lysis syndrome prevention and treatment"]],
        "summary": "",
    },
]


RICH_SUMMARIES = {

    # ═══════ TOPIC 3: NEUROLOGY, ENDOCRINE AND DIABETES ═════════════════

    "Stroke": (
        "Acute neurological deficit from cerebral infarction (about 85%) or "
        "haemorrhage (about 15%). "
        "Clinical features: sudden focal deficit fitting a vascular "
        "territory - anterior circulation gives hemiparesis, hemisensory "
        "loss, dysphasia or neglect; posterior gives ataxia, diplopia, "
        "vertigo and crossed signs. "
        "Ix: non-contrast CT immediately to exclude haemorrhage, then CT "
        "angiography and perfusion; BGL, since hypoglycaemia mimics stroke; "
        "ECG and prolonged monitoring for AF; carotid imaging. "
        "Mx: thrombolysis within 4.5 hours with BP below 185/110; "
        "thrombectomy up to 24 hours for large vessel occlusion with "
        "favourable imaging. Admit to a stroke unit - this alone improves "
        "outcomes as much as any drug. Haemorrhagic stroke needs BP lowering "
        "and anticoagulation reversal. "
        "Secondary prevention: antiplatelet or anticoagulation for AF, "
        "statin, BP control, carotid endarterectomy where indicated. "
        "DDx: Todd paralysis after seizure; hypoglycaemia; migraine with aura; "
        "subdural haematoma; hypertensive encephalopathy; tumour. "
        "Note: time is brain - the target is door-to-needle under 60 "
        "minutes, so investigation and treatment run in parallel."
    ),

    "Transient ischaemic attack": (
        "Transient focal neurological deficit from ischaemia without "
        "infarction - now defined on tissue rather than the old 24-hour "
        "clock, so imaging matters. "
        "Clinical features: sudden onset, resolving typically within an "
        "hour; amaurosis fugax, hemiparesis, dysphasia. "
        "Ix: urgent MRI with diffusion weighting is preferred - it "
        "reclassifies many TIAs as minor stroke; carotid imaging, ECG and "
        "prolonged rhythm monitoring, glucose, lipids. "
        "Mx: dual antiplatelet therapy with aspirin and clopidogrel for 21 "
        "days then single agent, started immediately in high-risk TIA; "
        "anticoagulate if AF; high-intensity statin; BP control; carotid "
        "endarterectomy within 2 weeks for symptomatic stenosis of 70-99%. "
        "Note: the risk of completed stroke is highest in the first 48 "
        "hours, so a TIA is an emergency, not a reassuring event. Australian "
        "guidance is for specialist assessment within 24 hours in high-risk "
        "patients. Advise not to drive and notify licensing requirements. "
        "Red flags: crescendo TIAs, or symptoms with a known critical "
        "stenosis, warrant admission."
    ),

    "Subarachnoid haemorrhage": (
        "Bleeding into the subarachnoid space, usually from a ruptured "
        "berry aneurysm. "
        "Risk factors: hypertension, smoking, family history, polycystic "
        "kidney disease, Ehlers-Danlos and Marfan syndromes. "
        "Clinical features: thunderclap headache reaching maximum intensity "
        "within a minute, classically the worst of the patient's life; "
        "vomiting, neck stiffness, photophobia, reduced consciousness, "
        "seizure. A sentinel bleed may precede it by days to weeks. "
        "Ix: non-contrast CT within 6 hours is close to 100% sensitive; "
        "beyond that, lumbar puncture at 12 hours looking for xanthochromia. "
        "CT angiography to define the aneurysm. "
        "Mx: neurosurgical referral; endovascular coiling or surgical "
        "clipping; nimodipine to reduce delayed cerebral ischaemia; blood "
        "pressure and analgesia control. "
        "Complications: rebleeding, delayed cerebral ischaemia from "
        "vasospasm at days 4-14, hydrocephalus, hyponatraemia from cerebral "
        "salt wasting or SIADH. "
        "Red flags: any thunderclap headache needs imaging, regardless of "
        "how well the patient looks by the time they are seen."
    ),

    "Epilepsy": (
        "Enduring predisposition to unprovoked seizures - two or more "
        "separated by 24 hours, or one with a high recurrence risk. "
        "Classification: focal (aware or impaired awareness, with or "
        "without progression to bilateral tonic-clonic) or generalised "
        "(tonic-clonic, absence, myoclonic, atonic). Classification drives "
        "drug choice, so it is not academic. "
        "Ix: EEG supports classification but a normal one does not exclude "
        "epilepsy; MRI brain for structural cause; BGL, UEC, calcium and "
        "toxicology to exclude provoked seizures; ECG, since cardiac syncope "
        "is the commonest mimic. "
        "Mx: antiseizure medication after a second seizure, or after a "
        "first with a structural lesion or epileptiform EEG. Levetiracetam or "
        "lamotrigine for both focal and generalised; sodium valproate is "
        "effective in generalised epilepsy but contraindicated in people who "
        "could become pregnant. "
        "Note: driving restrictions under Austroads apply from the first "
        "seizure and must be discussed and documented; the patient carries "
        "the reporting obligation in most states. "
        "Red flags: seizure over 5 minutes is status epilepticus - "
        "benzodiazepine, then a second-line agent."
    ),

    "Multiple sclerosis": (
        "Immune-mediated demyelinating disease of the central nervous "
        "system, disseminated in time and space. "
        "Epidemiology: onset 20-40; women about 3 times more than men; "
        "incidence rises with latitude, and Tasmania has among the highest "
        "rates in the world. "
        "Clinical features: optic neuritis with painful monocular visual "
        "loss; internuclear ophthalmoplegia; transverse myelitis; sensory "
        "disturbance; Lhermitte sign; Uhthoff phenomenon of transient "
        "worsening with heat. Fatigue and bladder dysfunction dominate later "
        "disability. "
        "Types: relapsing-remitting in about 85% at onset, most evolving to "
        "secondary progressive; primary progressive in the rest. "
        "Ix: MRI brain and cord with gadolinium showing periventricular, "
        "juxtacortical, infratentorial and spinal lesions; CSF "
        "oligoclonal bands; visual evoked potentials. "
        "Mx: high-dose methylprednisolone shortens relapses without altering "
        "outcome. Disease-modifying therapy is the substance of management "
        "and works best started early - from interferons and glatiramer "
        "through to natalizumab, ocrelizumab and cladribine. "
        "Note: vitamin D deficiency and smoking are modifiable risks for "
        "progression."
    ),

    "Parkinson disease": (
        "Neurodegenerative disease from dopaminergic neurone loss in the "
        "substantia nigra with alpha-synuclein Lewy body deposition. "
        "Clinical features: bradykinesia is obligatory, plus rest tremor at "
        "4-6 Hz, rigidity, or both. Asymmetry at onset is characteristic. "
        "Non-motor features precede motor ones by years - REM sleep behaviour "
        "disorder, hyposmia, constipation, depression. "
        "DDx: drug-induced parkinsonism (antipsychotics, metoclopramide - "
        "symmetrical and reversible), progressive supranuclear palsy (early "
        "falls, vertical gaze palsy), multiple system atrophy (autonomic "
        "failure), vascular parkinsonism (lower body predominant), essential "
        "tremor (postural not rest, improves with alcohol). "
        "Mx: levodopa with carbidopa is the most effective symptomatic "
        "therapy; dopamine agonists and MAO-B inhibitors are alternatives in "
        "younger patients to defer motor complications. Physiotherapy, "
        "speech therapy and exercise all have evidence. "
        "Note: never stop Parkinson medication abruptly in hospital, and "
        "never withhold it for fasting - missed doses cause severe akinesia "
        "and can precipitate a neuroleptic malignant-like syndrome."
    ),

    "Myasthenia gravis": (
        "Autoimmune disorder of the neuromuscular junction causing fatigable "
        "weakness. "
        "Pathophysiology: antibodies against the postsynaptic acetylcholine "
        "receptor in about 85%, or against MuSK in most of the rest, "
        "reducing endplate potential and causing failure with repeated use. "
        "Clinical features: fatigable weakness worsening through the day - "
        "ptosis and diplopia in most at onset, then bulbar involvement with "
        "dysarthria, dysphagia and nasal speech, then proximal limb and "
        "respiratory weakness. "
        "Ix: acetylcholine receptor and MuSK antibodies; repetitive nerve "
        "stimulation showing decrement, or single-fibre EMG; CT chest for "
        "thymoma, present in 10-15%; TFT. "
        "Mx: pyridostigmine for symptoms; prednisolone with azathioprine or "
        "mycophenolate for immunosuppression; thymectomy in thymoma and in "
        "younger seropositive patients. "
        "Note: many common drugs worsen myasthenia - aminoglycosides, "
        "macrolides, fluoroquinolones, beta-blockers, magnesium - so check "
        "any new prescription. "
        "Red flags: myasthenic crisis with respiratory failure needs "
        "monitoring of forced vital capacity, not oximetry, since saturation "
        "falls only after decompensation."
    ),

    "Guillain-Barré syndrome": (
        "Acute immune-mediated polyradiculoneuropathy causing ascending "
        "weakness, typically 1-3 weeks after infection. "
        "Causes: Campylobacter jejuni most often, then CMV, EBV, Mycoplasma "
        "and influenza. "
        "Clinical features: symmetrical ascending flaccid weakness with "
        "areflexia, developing over days to 4 weeks; sensory symptoms are "
        "usually mild relative to weakness; back and limb pain is common; "
        "autonomic instability with arrhythmia and labile blood pressure; "
        "facial and bulbar involvement. Miller Fisher variant gives "
        "ophthalmoplegia, ataxia and areflexia. "
        "Ix: nerve conduction studies showing demyelination; CSF with raised "
        "protein and normal cell count - albuminocytological dissociation - "
        "though this may be normal in the first week. Serial forced vital "
        "capacity is the key monitoring test. "
        "Mx: intravenous immunoglobulin or plasma exchange, equally "
        "effective and not combined; supportive care with VTE prophylaxis "
        "and cardiac monitoring. Corticosteroids do not work here. "
        "Red flags: falling FVC below about 20 mL/kg, bulbar weakness or "
        "autonomic instability means ICU. Respiratory failure develops "
        "before hypoxia appears on oximetry."
    ),

    "Syphilis": (
        "Sexually transmitted infection caused by the spirochaete Treponema "
        "pallidum; notifiable in every Australian jurisdiction and "
        "resurgent. Clinical features: primary, 9-90 days - painless "
        "indurated chancre at the inoculation site with regional "
        "lymphadenopathy, heals spontaneously; secondary, 6-12 weeks - "
        "maculopapular rash involving palms and soles, condylomata lata, "
        "alopecia, hepatitis, uveitis; latent - asymptomatic with positive "
        "serology; tertiary, 10-30 years - gummas, aortitis with aortic "
        "regurgitation, neurosyphilis. Ix: dark-field microscopy or PCR of "
        "a lesion swab; treponemal EIA or TPHA screens and stays positive "
        "for life; RPR or VDRL titres track activity and response. Mx: "
        "benzathine benzylpenicillin 1.8 g IM single dose for primary, "
        "secondary and early latent; three weekly doses for late latent and "
        "tertiary; benzylpenicillin IV for 15 days in neurosyphilis. Note: "
        "tabes dorsalis gives a wide-based gait, lancinating pains and "
        "Argyll Robertson pupils, which accommodate but do not react to "
        "light. Red flags: Jarisch-Herxheimer reaction within 24 hours of "
        "the first dose - fever, rigors, hypotension; screen every "
        "pregnancy for congenital syphilis."
    ),

    "Neuroleptic malignant syndrome": (
        "Potentially fatal idiosyncratic reaction to antipsychotics, "
        "typical more than atypical, or to dopamine agonist withdrawal; D2 "
        "blockade in striatum and hypothalamus. Sx (tetrad): hyperthermia "
        "above 38°C, often above 40°C; lead-pipe rigidity; altered "
        "consciousness progressing to coma; autonomic instability with "
        "diaphoresis, tachycardia, labile BP and tachypnoea. Onset: hours "
        "to days after starting or increasing an antipsychotic, or stopping "
        "a dopaminergic. Ix: CK often above 1000 and can exceed 100,000; "
        "leukocytosis; raised LFTs; metabolic acidosis; myoglobinuria "
        "progressing to AKI. Ddx: serotonin syndrome - clonus and "
        "hyperreflexia, onset under 24 hours; malignant hyperthermia - "
        "inhalational anaesthetic or suxamethonium; anticholinergic "
        "toxidrome - dry skin, normal reflexes. Mx: stop the causative "
        "drug; IV fluids, active cooling, respiratory support; "
        "bromocriptine or dantrolene for rigidity; benzodiazepines for "
        "agitation; ECT if refractory or catatonic. Red flags: recovery "
        "takes days to weeks; rechallenge with a different antipsychotic no "
        "sooner than 2 weeks."
    ),

    "Horner syndrome": (
        "Interruption of the oculosympathetic pathway, producing ipsilateral "
        "partial ptosis, miosis and anhidrosis. "
        "Causes: first-order, hypothalamus to C8-T2 - lateral medullary "
        "infarct, MS, syringomyelia, cord tumour; second-order preganglionic "
        "- Pancoast tumour, cervical rib, neck surgery, neuroblastoma in "
        "children; third-order postganglionic - carotid dissection, "
        "cavernous sinus lesion, cluster headache. "
        "Clinical features: partial ptosis from denervation of the superior "
        "tarsal muscle, not the complete ptosis of a third nerve palsy; "
        "miosis with dilation lag and anisocoria greater in dim light; "
        "pupillary light response preserved; iris heterochromia if "
        "congenital. "
        "Ix: apraclonidine is the test of choice, reversing anisocoria "
        "through denervation supersensitivity; hydroxyamphetamine separates "
        "third-order from more proximal lesions; imaging follows the level "
        "suspected - CT or MR angiography of the neck, CT chest for an "
        "apical lesion. "
        "Note: anhidrosis localises - hemibody in first-order, face in "
        "second-order, absent in third-order. "
        "Red flags: painful Horner syndrome is carotid dissection until "
        "excluded; new Horner syndrome in a child needs urinary "
        "catecholamines for neuroblastoma."
    ),

    "Diabetic ketoacidosis": (
        "Acute hyperglycaemic emergency from absolute insulin deficiency, "
        "with ketosis and metabolic acidosis. "
        "Criteria: hyperglycaemia (though euglycaemic DKA occurs); ketonaemia "
        "3.0 mmol/L or more; pH below 7.3 or bicarbonate below 15. "
        "Triggers: infection, missed insulin, new-onset type 1 diabetes, "
        "myocardial infarction, and SGLT2 inhibitors. "
        "Clinical features: polyuria and thirst; vomiting and abdominal pain; "
        "Kussmaul respiration; ketotic breath; drowsiness. "
        "Mx: fluid first - the deficit is usually 5-7 L. Then fixed-rate "
        "insulin at 0.1 units/kg/h. Potassium from the outset unless above "
        "5.5, since total body potassium is depleted however normal the level "
        "looks. Add glucose-containing fluid once BGL falls below 14 while "
        "continuing insulin, which is clearing ketones, not glucose. "
        "Note: euglycaemic DKA on SGLT2 inhibitors is easily missed - check "
        "ketones in any unwell patient on one regardless of the glucose. "
        "Red flags: cerebral oedema, mainly in children and after rapid "
        "osmolar shifts; hypokalaemia is the commonest avoidable cause of "
        "death."
    ),

    "Diabetes mellitus": (
        "Chronic hyperglycaemia from insulin resistance with progressive "
        "beta-cell failure. "
        "Ix: HbA1c of 6.5% or above, fasting glucose 7.0 or above, or a "
        "2-hour OGTT value of 11.1 or above - confirmed on a second sample "
        "unless symptomatic. HbA1c is unreliable in haemoglobinopathy, "
        "recent transfusion and chronic kidney disease. "
        "Mx: lifestyle plus metformin first-line for most. Then choose by "
        "comorbidity rather than by HbA1c alone - an SGLT2 inhibitor for "
        "heart failure or chronic kidney disease, a GLP-1 receptor agonist "
        "for obesity or established cardiovascular disease. Target HbA1c is "
        "around 7% generally, relaxed in the frail or in hypoglycaemia "
        "unawareness. "
        "Monitoring: HbA1c 3- to 6-monthly; annual retinal screening, urine "
        "ACR, eGFR, foot examination with monofilament, and lipids. "
        "Note: PBS criteria govern access to SGLT2 inhibitors and GLP-1 "
        "agonists in Australia and change periodically - check before "
        "prescribing. Metformin needs holding around iodinated contrast and "
        "in acute illness. "
        "Red flags: rapid weight loss or ketosis suggests type 1 or "
        "pancreatic disease, not type 2."
    ),

    "Hypothyroidism": (
        "Deficiency of thyroid hormone, most often from autoimmune "
        "thyroiditis. "
        "Causes: Hashimoto thyroiditis is commonest in iodine-replete "
        "countries; also post-thyroidectomy, radioiodine, amiodarone, "
        "lithium, and central causes from pituitary disease. "
        "Clinical features: fatigue, cold intolerance, weight gain; "
        "constipation and dry skin; menorrhagia; depression and cognitive "
        "slowing; bradycardia with delayed reflex relaxation. Onset is "
        "insidious and often attributed elsewhere for months. "
        "Ix: TSH first - raised with low free T4 in primary disease; raised "
        "TSH with normal T4 is subclinical. TPO antibodies confirm autoimmune "
        "cause. Low TSH with low T4 means central hypothyroidism. "
        "Mx: levothyroxine, starting low in the elderly or those with "
        "ischaemic heart disease, retesting TSH after 6-8 weeks. Take on an "
        "empty stomach, separated from calcium, iron and proton pump "
        "inhibitors. "
        "Note: in pregnancy, requirements rise by 25-50% from early in the "
        "first trimester and undertreatment affects fetal neurodevelopment - "
        "increase the dose promptly and check TSH early."
    ),

    "Hyperthyroidism": (
        "Excess thyroid hormone, most often from Graves disease. "
        "Causes: Graves disease (TSH receptor antibodies), toxic multinodular "
        "goitre, toxic adenoma, thyroiditis with a transient release phase, "
        "amiodarone, and excess levothyroxine. "
        "Clinical features: weight loss with preserved appetite; heat "
        "intolerance and sweating; tremor and anxiety; palpitations or AF; "
        "diarrhoea; goitre. Graves adds orbitopathy and pretibial myxoedema, "
        "which no other cause produces. "
        "Ix: suppressed TSH with raised free T4 or T3; TSH receptor antibodies "
        "for Graves; uptake scan separates Graves and toxic nodules (high) "
        "from thyroiditis (low) - which decides whether antithyroid drugs "
        "help at all. "
        "Mx: carbimazole, or propylthiouracil in the first trimester of "
        "pregnancy; beta-blocker for symptom control; then radioiodine or "
        "surgery for definitive treatment. "
        "Note: warn every patient starting carbimazole to stop and seek an "
        "urgent FBC with fever or sore throat - agranulocytosis is rare but "
        "can be fatal. "
        "Red flags: thyroid storm - fever, agitation, tachyarrhythmia and "
        "heart failure - has high mortality and needs ICU."
    ),

    "Addison disease": (
        "Primary adrenal insufficiency with deficient cortisol and "
        "aldosterone. "
        "Causes: autoimmune adrenalitis in developed countries; tuberculosis "
        "worldwide; adrenal haemorrhage, metastases, and adrenoleukodystrophy. "
        "Clinical features: insidious fatigue, anorexia and weight loss; "
        "nausea and abdominal pain; salt craving; postural hypotension; "
        "hyperpigmentation of palmar creases and buccal mucosa, which "
        "distinguishes primary from secondary insufficiency. "
        "Ix: hyponatraemia with hyperkalaemia is characteristic; early "
        "morning cortisol, with a short synacthen test to confirm; ACTH is "
        "raised in primary disease and low in secondary; adrenal antibodies; "
        "imaging if not autoimmune. "
        "Mx: hydrocortisone in divided doses replicating diurnal rhythm, plus "
        "fludrocortisone. Sick day rules - double the dose during illness - "
        "with a parenteral emergency kit and alert bracelet. "
        "Red flags: adrenal crisis presents with hypotension, vomiting and "
        "hyponatraemia. Give intravenous hydrocortisone and fluid "
        "immediately on suspicion; do not wait for cortisol results, which "
        "can be taken first but must not delay treatment."
    ),

    "Cushing syndrome": (
        "Clinical state of chronic glucocorticoid excess. "
        "Causes: exogenous corticosteroid is overwhelmingly the commonest "
        "and is often overlooked. Endogenous causes are ACTH-dependent - "
        "pituitary adenoma (Cushing disease) or ectopic ACTH from small cell "
        "lung cancer - or ACTH-independent adrenal adenoma or carcinoma. "
        "Clinical features: central obesity with thin limbs; moon face and "
        "interscapular fat pad; hypertension, hyperglycaemia, osteoporosis. "
        "The discriminating features are proximal myopathy, wide violaceous "
        "striae and easy bruising, since obesity alone produces the rest. "
        "Ix: confirm cortisol excess with 24-hour urinary free cortisol, "
        "late-night salivary cortisol, or overnight dexamethasone "
        "suppression. Then ACTH to establish dependence, and image "
        "accordingly. "
        "Mx: withdraw exogenous steroid gradually where that is the cause; "
        "otherwise transsphenoidal surgery, adrenalectomy, or treatment of "
        "the ectopic tumour. "
        "Note: ectopic ACTH often presents with hypokalaemic alkalosis and "
        "pigmentation rather than the classic habitus, because it develops "
        "too fast for the phenotype to appear."
    ),

    "Syndrome of inappropriate antidiuretic hormone secretion": (
        "Euvolaemic hypotonic hyponatraemia from unsuppressed ADH. "
        "Causes: malignancy especially small cell lung cancer; CNS disease "
        "including stroke, haemorrhage and meningitis; pulmonary disease; "
        "and drugs - SSRIs, carbamazepine, and thiazides among others. "
        "Criteria: hyponatraemia with low serum osmolality, "
        "inappropriately concentrated urine above 100 mOsm/kg, urinary "
        "sodium above 30 mmol/L, clinical euvolaemia, and normal thyroid, "
        "adrenal and renal function. "
        "Clinical features: often asymptomatic when chronic; nausea, "
        "headache, confusion, and seizure or coma when severe or rapid. Rate "
        "of fall matters more than the absolute level. "
        "Mx: treat the cause; fluid restriction first-line; salt tablets or "
        "tolvaptan in resistant cases. Hypertonic saline only for severe "
        "symptoms. "
        "Note: correct no faster than 8-10 mmol/L in 24 hours - overly rapid "
        "correction of chronic hyponatraemia causes osmotic demyelination "
        "syndrome, which is irreversible. Volume status is what separates "
        "SIADH from hypovolaemic and hypervolaemic hyponatraemia, so assess "
        "it before treating."
    ),

    # ═══════════ TOPIC 7: ONCOLOGY AND HAEMATOLOGY ══════════════════════

    "Iron deficiency anaemia": (
        "Anaemia from depleted iron stores, the commonest anaemia worldwide. "
        "Causes: blood loss is the assumption until disproven - menstrual in "
        "premenopausal women, gastrointestinal otherwise. Also malabsorption "
        "(coeliac disease, atrophic gastritis, bariatric surgery), poor "
        "intake, and increased demand in pregnancy and infancy. "
        "Clinical features: fatigue, dyspnoea, pallor; angular stomatitis, "
        "glossitis, koilonychia and pica when chronic. "
        "Ix: microcytic hypochromic film; ferritin is the single best test - "
        "low is diagnostic, but it is an acute-phase reactant so a normal "
        "level does not exclude deficiency during inflammation. Transferrin "
        "saturation below 16% supports it. "
        "Mx: oral iron, alternate-day dosing giving better absorption than "
        "daily by avoiding a hepcidin rise; intravenous iron for intolerance "
        "or malabsorption. Recheck at 2-4 weeks, and continue 3 months past "
        "normalisation to refill stores. "
        "Note: iron deficiency anaemia in a man of any age, or a "
        "postmenopausal woman, mandates gastroscopy and colonoscopy - it is "
        "colorectal cancer until proven otherwise. Also test for coeliac "
        "disease."
    ),

    "Vitamin B12 deficiency": (
        "Deficiency causing megaloblastic anaemia and, independently, "
        "neurological disease. "
        "Causes: pernicious anaemia (autoimmune loss of intrinsic factor); "
        "gastrectomy or ileal resection; Crohn disease; metformin and "
        "long-term proton pump inhibitors; strict vegan diet. "
        "Clinical features: fatigue and pallor; glossitis; and neurological "
        "features - symmetrical paraesthesiae, loss of proprioception and "
        "vibration from subacute combined degeneration of the cord, ataxia, "
        "and cognitive or mood change. "
        "Ix: macrocytic anaemia with hypersegmented neutrophils; low serum "
        "B12; raised methylmalonic acid and homocysteine confirm functional "
        "deficiency when B12 is borderline. Intrinsic factor antibodies are "
        "specific but insensitive for pernicious anaemia. "
        "Mx: intramuscular hydroxocobalamin, loading then maintenance; "
        "lifelong if the cause is not reversible. High-dose oral is adequate "
        "in dietary deficiency. "
        "Note: neurological disease occurs without anaemia and can be "
        "irreversible if treatment is delayed - do not wait for a low "
        "haemoglobin. Never replace folate alone in combined deficiency; it "
        "corrects the anaemia while the cord degeneration progresses."
    ),

    "Multiple myeloma": (
        "Clonal plasma cell malignancy producing monoclonal immunoglobulin "
        "and end-organ damage. "
        "Epidemiology: median onset around 70; preceded by monoclonal "
        "gammopathy of undetermined significance in essentially all cases. "
        "Clinical features: CRAB - hyperCalcaemia, Renal impairment, Anaemia, "
        "Bone lesions - with bone pain, fracture and recurrent infection. "
        "Ix: serum and urine electrophoresis with immunofixation; serum free "
        "light chain ratio; FBC, UEC, calcium, beta-2 microglobulin; "
        "whole-body low-dose CT rather than skeletal survey; marrow biopsy "
        "for plasma cell percentage and cytogenetics. "
        "Mx: induction with a proteasome inhibitor, an immunomodulatory drug "
        "and dexamethasone, then autologous stem cell transplant if fit, then "
        "maintenance. Bisphosphonates for skeletal protection, plus "
        "analgesia and radiotherapy for painful lesions. "
        "Note: the rouleaux and raised ESR often come before anything else, "
        "and myeloma is a leading cause of an unexplained normocytic anaemia "
        "with renal impairment in an older patient. "
        "Red flags: back pain with neurological signs is cord compression; "
        "hypercalcaemia and hyperviscosity are both emergencies."
    ),

    "Hodgkin lymphoma": (
        "B-cell lymphoma defined by Reed-Sternberg cells in a reactive "
        "inflammatory background. "
        "Epidemiology: bimodal, peaking in the 20s and again after 60; "
        "associated with Epstein-Barr virus. "
        "Clinical features: painless, rubbery cervical or supraclavicular "
        "lymphadenopathy spreading contiguously between nodal groups; "
        "mediastinal mass; B symptoms - fever, drenching night sweats, weight "
        "loss over 10% in 6 months. Alcohol-induced nodal pain and pruritus "
        "are uncommon but characteristic. "
        "Ix: excisional node biopsy, not fine-needle aspiration, since "
        "architecture is needed; PET-CT for staging; FBC, ESR, LDH, LFT, "
        "HIV and hepatitis serology. "
        "Mx: ABVD chemotherapy with or without radiotherapy, guided by stage "
        "and interim PET response. Cure rates are high, above 80% overall. "
        "Note: contiguous spread and a young peak distinguish it clinically "
        "from non-Hodgkin lymphoma, which skips nodal groups and is more "
        "often extranodal. "
        "Complications: long-term survivorship risks matter as much as the "
        "disease - secondary malignancy, cardiotoxicity from anthracyclines, "
        "bleomycin lung toxicity, and infertility, so counsel on fertility "
        "preservation before treatment."
    ),

    "Non-Hodgkin lymphoma": (
        "Heterogeneous group of lymphoid malignancies, mostly B-cell, "
        "spanning indolent to highly aggressive behaviour. "
        "Classification: aggressive - diffuse large B-cell lymphoma "
        "(commonest), Burkitt, mantle cell; indolent - follicular, marginal "
        "zone, small lymphocytic. The split determines everything about "
        "management. "
        "Clinical features: painless lymphadenopathy with non-contiguous "
        "spread; extranodal involvement is common - gut, skin, CNS, testis; "
        "B symptoms; cytopenias from marrow involvement. "
        "Ix: excisional biopsy with immunohistochemistry; PET-CT; bone marrow "
        "biopsy; LDH (prognostic); HIV, hepatitis B and C serology before "
        "rituximab. "
        "Mx: aggressive disease is treated with curative intent - R-CHOP for "
        "diffuse large B-cell lymphoma. Indolent disease is often watched, "
        "since treating an asymptomatic follicular lymphoma does not improve "
        "survival. "
        "Note: the counterintuitive part is that aggressive lymphomas are "
        "curable and indolent ones generally are not - fast-growing tumours "
        "are more chemosensitive. "
        "Red flags: hepatitis B reactivation with rituximab can be fatal, so "
        "screen and give antiviral prophylaxis."
    ),

    "Chronic lymphocytic leukaemia": (
        "Clonal proliferation of mature but functionally incompetent B "
        "lymphocytes; the commonest leukaemia in adults in Australia. "
        "Epidemiology: median age around 70; often found incidentally on a "
        "routine FBC. "
        "Clinical features: frequently asymptomatic; otherwise "
        "lymphadenopathy, splenomegaly, fatigue, recurrent infection from "
        "hypogammaglobulinaemia, and later marrow failure. "
        "Ix: persistent lymphocytosis above 5 x 10^9/L with smudge cells on "
        "film; flow cytometry showing CD5, CD19, CD23 co-expression is "
        "diagnostic; FISH for del(17p) and TP53, which predict poor response "
        "to chemoimmunotherapy; direct antiglobulin test. "
        "Mx: watch and wait while asymptomatic - early treatment does not "
        "prolong survival. Treat for progressive cytopenias, bulky or "
        "symptomatic disease, or constitutional symptoms, with targeted "
        "agents such as BTK or BCL-2 inhibitors. "
        "Complications: autoimmune haemolytic anaemia and immune "
        "thrombocytopenia; recurrent infection; Richter transformation to "
        "aggressive lymphoma, suggested by rapid nodal growth with fever and "
        "a rising LDH."
    ),

    "Acute myeloid leukaemia": (
        "Clonal proliferation of myeloid blasts with arrested "
        "differentiation, causing rapid marrow failure. "
        "Epidemiology: median onset around 68; risk raised by prior "
        "chemotherapy, radiation, myelodysplasia and Down syndrome. "
        "Clinical features: days to weeks of fatigue, infection and "
        "bleeding, reflecting anaemia, neutropenia and thrombocytopenia; gum "
        "hypertrophy and skin infiltration in monocytic subtypes. "
        "Ix: blasts on film, often with Auer rods; marrow with 20% or more "
        "blasts; flow cytometry, cytogenetics and molecular testing (FLT3, "
        "NPM1, CEBPA) drive both prognosis and drug choice; coagulation "
        "screen, LDH, urate. "
        "Mx: intensive induction chemotherapy then consolidation or "
        "allogeneic transplant in fit patients; hypomethylating agents with "
        "venetoclax in those unfit for intensive therapy. "
        "Note: acute promyelocytic leukaemia is the subtype to recognise "
        "immediately - it presents with DIC and life-threatening bleeding, "
        "and is treated with all-trans retinoic acid started on suspicion "
        "rather than on confirmation. "
        "Red flags: fever with neutropenia is a medical emergency; "
        "hyperleukocytosis causes leukostasis with hypoxia and confusion."
    ),

    "Chronic myeloid leukaemia": (
        "Myeloproliferative neoplasm driven by the BCR-ABL1 fusion from the "
        "Philadelphia chromosome, t(9;22). "
        "Clinical features: often incidental leukocytosis; otherwise "
        "fatigue, weight loss, sweats, and splenomegaly which may be "
        "massive and cause early satiety or left upper quadrant pain. "
        "Phases: chronic (most at diagnosis), accelerated, and blast crisis "
        "resembling acute leukaemia. "
        "Ix: marked leukocytosis with the full spectrum of myeloid "
        "precursors and basophilia; low leukocyte alkaline phosphatase; "
        "BCR-ABL1 by PCR or cytogenetics is diagnostic. "
        "Mx: a tyrosine kinase inhibitor - imatinib, or a second-generation "
        "agent - with molecular monitoring of BCR-ABL1 transcript levels "
        "against defined milestones. Some with sustained deep molecular "
        "response can attempt treatment-free remission. "
        "Note: CML is the model of targeted therapy - a disease that was "
        "uniformly fatal now has near-normal life expectancy on a tablet, "
        "and adherence is the main determinant of outcome. "
        "Red flags: rising basophils, blasts or a rising transcript level "
        "signal progression."
    ),

    "Immune thrombocytopenic purpura": (
        "Autoimmune platelet destruction and impaired production, with "
        "isolated thrombocytopenia and no alternative cause. "
        "Clinical features: petechiae, purpura, mucosal bleeding - "
        "epistaxis, gum bleeding, menorrhagia. Bleeding risk is low above "
        "30 x 10^9/L. Children typically have an abrupt post-viral course "
        "that resolves; adults are usually chronic. "
        "Ix: a diagnosis of exclusion. Isolated thrombocytopenia on FBC with "
        "a normal film apart from large platelets; exclude pseudo-"
        "thrombocytopenia from EDTA clumping by repeating in citrate. Test "
        "HIV, hepatitis C and Helicobacter pylori. Marrow biopsy only in "
        "atypical cases. "
        "Mx: treat bleeding or a count below about 20-30 x 10^9/L, not the "
        "number alone. Prednisolone or dexamethasone first-line, with IVIg "
        "when a rapid rise is needed; then thrombopoietin receptor agonists, "
        "rituximab or splenectomy. "
        "Note: platelet transfusion is largely ineffective and reserved for "
        "life-threatening bleeding, since transfused platelets are destroyed "
        "by the same process."
    ),

    "Disseminated intravascular coagulation": (
        "Systemic activation of coagulation that consumes platelets and "
        "clotting factors, producing simultaneous thrombosis and bleeding. "
        "Causes: sepsis (commonest); major trauma; obstetric catastrophe "
        "including abruption and amniotic fluid embolism; malignancy, "
        "especially acute promyelocytic leukaemia. "
        "Pathophysiology: massive tissue factor release drives widespread "
        "microthrombi, which consume the substrate needed for haemostasis - "
        "hence bleeding in a hypercoagulable state. "
        "Clinical features: oozing from cannula and venepuncture sites, "
        "purpura fulminans, and organ dysfunction from microvascular "
        "thrombosis. "
        "Ix: thrombocytopenia, prolonged PT and APTT, low fibrinogen, "
        "markedly raised D-dimer, schistocytes on film. The trend across "
        "serial results is more informative than any single set. "
        "Mx: treat the underlying cause, which is the only definitive "
        "therapy. Support with platelets, fresh frozen plasma and "
        "cryoprecipitate guided by bleeding rather than by numbers alone. "
        "Note: fibrinogen falls late and a normal level early does not "
        "exclude DIC - it is an acute-phase reactant, so a normal value in a "
        "septic patient may already represent a fall."
    ),

    "Febrile neutropenia": (
        "Fever in a neutropenic patient - an oncological emergency, since "
        "the usual signs of infection are absent when neutrophils are. "
        "Definition: single temperature of 38.3 degrees, or 38.0 sustained "
        "over an hour, with neutrophils below 0.5 x 10^9/L or expected to "
        "fall below it. "
        "Clinical features: fever may be the only sign - there is no pus, "
        "little erythema, and often no localising feature. Hypotension may "
        "be the first indication of sepsis. "
        "Ix: blood cultures from peripheral and any central line before "
        "antibiotics; FBC, UEC, LFT, lactate; chest X-ray; cultures directed "
        "by symptoms. Do not delay treatment for results. "
        "Mx: broad-spectrum antipseudomonal beta-lactam - piperacillin-"
        "tazobactam or cefepime - within one hour of presentation. Add "
        "vancomycin for suspected line infection or haemodynamic "
        "instability. G-CSF where prophylaxis is indicated. "
        "Note: the one-hour target matters more than antibiotic choice; "
        "mortality rises measurably with each hour of delay. Any patient on "
        "chemotherapy with a fever needs assessment now, not in the morning."
    ),

    "Tumour lysis syndrome": (
        "Metabolic emergency from massive tumour cell breakdown releasing "
        "intracellular contents. "
        "Risk factors: bulky, rapidly proliferating, chemosensitive disease - "
        "Burkitt lymphoma, ALL, AML with high white count - plus "
        "pre-existing renal impairment or volume depletion. Usually within "
        "72 hours of starting treatment, occasionally spontaneous. "
        "Clinical features: from the electrolyte derangement - arrhythmia, "
        "tetany, seizures, and acute kidney injury from urate and calcium "
        "phosphate deposition. "
        "Ix: hyperkalaemia, hyperphosphataemia, hyperuricaemia and "
        "consequent hypocalcaemia, with rising creatinine. Monitor 6- to "
        "12-hourly in high-risk patients. "
        "Mx: prevention is the whole game - vigorous intravenous hydration, "
        "with allopurinol for moderate risk and rasburicase for high risk or "
        "established disease. Treat hyperkalaemia urgently; dialysis for "
        "refractory derangement or oliguric renal failure. "
        "Note: do not give calcium for asymptomatic hypocalcaemia - it "
        "precipitates with the high phosphate and worsens renal injury. "
        "Rasburicase is contraindicated in G6PD deficiency."
    ),

    "Spinal cord compression": (
        "Compression of the cord or cauda equina by tumour, most often from "
        "vertebral metastasis. "
        "Causes: breast, lung and prostate primaries account for most; also "
        "myeloma, renal and lymphoma. "
        "Clinical features: back pain first, typically for weeks and often "
        "worse lying flat or on coughing, then neurological signs - limb "
        "weakness, sensory level, and finally bladder and bowel dysfunction. "
        "Ix: whole-spine MRI within 24 hours, and sooner with neurological "
        "signs. Whole spine, because multiple levels are involved in about a "
        "third and imaging only the painful level misses them. "
        "Mx: dexamethasone 16 mg immediately on suspicion, before imaging "
        "confirms it, with proton pump cover and glucose monitoring. Then "
        "urgent radiotherapy or surgical decompression depending on "
        "stability, prognosis and tissue diagnosis. "
        "Note: pretreatment ambulatory status is the strongest predictor of "
        "walking afterwards, so the window for useful intervention closes "
        "with the loss of power, not with the onset of pain. "
        "Red flags: new back pain in anyone with known malignancy is cord "
        "compression until imaging says otherwise."
    ),

    "Hypercalcaemia": (
        "Raised serum calcium. Primary hyperparathyroidism and malignancy "
        "account for about 90% of cases between them - the first dominates in "
        "outpatients, the second in inpatients. "
        "Mechanism: in malignancy, PTH-related peptide in about 80% - squamous "
        "cell, renal and breast; osteolytic metastases in myeloma; rarely "
        "tumour calcitriol in lymphoma. "
        "Clinical features: the classic bones, stones, groans and psychic "
        "moans - polyuria and thirst, nausea, constipation, confusion, "
        "weakness. Onset is often rapid, so symptoms appear at lower levels "
        "than in primary hyperparathyroidism. "
        "Ix: corrected calcium or ionised calcium; PTH is suppressed in "
        "malignancy and raised or inappropriately normal in primary "
        "hyperparathyroidism; UEC, phosphate. "
        "Mx: aggressive intravenous normal saline first - these patients are "
        "profoundly volume-deplete from calcium-induced polyuria. Then a "
        "bisphosphonate (zoledronic acid), which takes 2-4 days to work, or "
        "denosumab in renal impairment. Calcitonin for rapid but transient "
        "control. "
        "Note: avoid loop diuretics until volume-replete - they were "
        "traditionally taught but worsen dehydration and are now reserved "
        "for fluid overload."
    ),

    # ══════════════════ TOPIC 4: RHEUMATOLOGY ═══════════════════════════

    "Polymyalgia rheumatica": (
        "Inflammatory condition causing aching and morning stiffness of the "
        "shoulder and hip girdles and neck, without true weakness. "
        "Epidemiology: age over 50, peak 70s; women 3x more than men. "
        "Pathophysiology: inflames peri-articular structures, not muscle - "
        "hence normal CK and preserved strength. "
        "Clinical features: bilateral girdle ache, morning stiffness over 45 "
        "min; constitutional symptoms. "
        "Ix: raised ESR/CRP, normocytic anaemia; CK normal; RF and anti-CCP "
        "negative. "
        "Mx: prednisolone 12.5-25 mg daily, tapered over 12-24 months on "
        "symptoms not ESR; bone protection. "
        "Note: steroid response is dramatic and near-diagnostic - no "
        "substantial improvement within a week means another diagnosis. "
        "Red flags: headache, jaw claudication or visual symptoms mean giant "
        "cell arteritis - high-dose steroids same day."
    ),

    "Giant cell arteritis": (
        "Granulomatous large-vessel vasculitis of the aorta and branches, "
        "especially the extracranial carotid branches. "
        "Epidemiology: over 50, peak 70-80; women > men; half have "
        "polymyalgia rheumatica. "
        "Clinical features: new temporal headache, scalp tenderness, jaw "
        "claudication, amaurosis fugax or sudden painless visual loss from "
        "anterior ischaemic optic neuropathy. "
        "Ix: ESR and CRP raised; temporal artery ultrasound halo sign; biopsy "
        "is the diagnostic standard. "
        "Mx: high-dose prednisolone immediately on suspicion - IV "
        "methylprednisolone first if visual symptoms; add aspirin and bone "
        "protection. "
        "Note: biopsy stays positive 1-2 weeks after starting steroids, so "
        "treatment never waits for it. "
        "Red flags: any visual symptom is an emergency - vision rarely "
        "returns and the other eye is at risk within days."
    ),

    "Dermatomyositis": (
        "Idiopathic inflammatory myopathy: symmetrical proximal weakness "
        "plus characteristic skin changes. "
        "Epidemiology: bimodal 5-15 and 40-60 yr; women > men. "
        "Pathophysiology: complement-mediated microangiopathy of endomysial "
        "capillaries, giving perifascicular atrophy. "
        "Clinical features: proximal weakness over weeks to months (deltoids, "
        "hip flexors, neck flexors); Gottron papules and heliotrope eruption "
        "are pathognomonic; photodistributed poikiloderma (shawl, V and "
        "Holster signs); ILD, myocarditis, dysphagia. "
        "Ix: CK 2-100x normal; ANA; myositis-specific antibodies (anti-Mi-2 "
        "good prognosis, anti-Jo-1 ILD, anti-MDA5 rapidly progressive ILD, "
        "anti-TIF1-gamma malignancy); muscle biopsy diagnostic. "
        "Mx: prednisolone plus methotrexate or azathioprine; IVIg if "
        "refractory. "
        "Note: adult disease carries markedly raised malignancy risk, "
        "highest in the first 3 years - CT chest, abdomen and pelvis plus "
        "age-appropriate screening."
    ),

    "Polymyositis": (
        "Idiopathic inflammatory myopathy causing symmetrical proximal "
        "weakness without the skin changes of dermatomyositis. "
        "Epidemiology: peak 30-60 yr, rare in children; women > men. "
        "Pathophysiology: CD8 T-cell cytotoxicity with endomysial "
        "inflammation - cell-mediated, unlike dermatomyositis. "
        "Clinical features: insidious proximal weakness of shoulder and hip "
        "girdles; dysphagia; no rash. "
        "Ix: CK markedly raised; ANA and anti-Jo-1; muscle biopsy shows "
        "endomysial infiltrate invading non-necrotic fibres. "
        "Differential: inclusion body myositis (older, asymmetric, distal - "
        "finger flexors and quadriceps - and steroid-unresponsive); "
        "immune-mediated necrotising myopathy including statin-associated "
        "anti-HMGCR; hypothyroid and drug-induced myopathy. "
        "Note: a diagnosis of exclusion, and diagnosed far more often than "
        "it occurs - asymmetric, distal or steroid-unresponsive weakness "
        "should prompt reconsideration."
    ),

    "Rheumatoid arthritis": (
        "Chronic symmetrical inflammatory polyarthritis of small joints with "
        "an erosive synovitis and systemic features. "
        "Epidemiology: onset 30-50 yr; women 3x more than men; smoking is "
        "the strongest modifiable risk. "
        "Pathophysiology: citrullinated self-proteins drive anti-CCP; synovial "
        "pannus releases proteases and RANKL, eroding bone. "
        "Clinical features: symmetrical MCP, PIP, wrist and MTP swelling; "
        "morning stiffness over an hour, easing with use; DIPs spared. "
        "Extra-articular: nodules, ILD, scleritis. "
        "Ix: anti-CCP (more specific, predicts erosions), RF, raised "
        "ESR/CRP; X-ray periarticular osteopenia and marginal erosions. "
        "Mx: methotrexate within weeks of diagnosis, treat-to-target to "
        "remission; escalate to biologic or JAK inhibitor per PBS; steroids "
        "only to bridge. "
        "Note: the window to prevent erosions is months - suspected "
        "inflammatory arthritis needs urgent referral, not a trial of NSAIDs."
    ),

    "Systemic lupus erythematosus": (
        "Multisystem autoimmune disease from immune complex deposition, "
        "relapsing and remitting. "
        "Epidemiology: women 9x more than men, reproductive years; more "
        "common and more severe in Aboriginal and Torres Strait Islander "
        "people. "
        "Clinical features: malar rash sparing nasolabial folds, "
        "photosensitivity, oral ulcers, alopecia; non-erosive arthritis; "
        "serositis; lupus nephritis; cytopenias. "
        "Ix: ANA screens (a negative makes lupus very unlikely); anti-dsDNA "
        "and anti-Sm are specific, dsDNA titre tracks activity; low C3/C4 in "
        "flares; urinalysis with ACR at every visit. "
        "Mx: hydroxychloroquine for nearly everyone - reduces flares, damage "
        "and mortality; mycophenolate or cyclophosphamide for "
        "organ-threatening disease. "
        "Note: lupus nephritis is usually asymptomatic until advanced, so "
        "routine urinalysis is what detects it."
    ),

    "Gout": (
        "Inflammatory arthritis from monosodium urate crystal deposition. "
        "Epidemiology: men >> premenopausal women; markedly increased in "
        "Aboriginal and Torres Strait Islander, Maori and Pacific peoples. "
        "Pathophysiology: urate crystals activate the NLRP3 inflammasome, "
        "releasing IL-1 beta. "
        "Clinical features: abrupt exquisitely painful monoarthritis peaking "
        "within 24 h, classically first MTP (podagra); tophi and erosions "
        "later. "
        "Ix: aspiration shows negatively birefringent needles and excludes "
        "sepsis; urate may be normal during an attack - recheck at 2 weeks. "
        "Mx: NSAID, colchicine or prednisolone for the attack. Allopurinol for "
        "recurrent attacks, tophi or erosions - target urate below "
        "0.36 mmol/L, with colchicine cover. "
        "Note: check HLA-B*5801 in high-risk ancestries before allopurinol. "
        "Red flags: a hot swollen joint is septic arthritis until aspiration "
        "says otherwise - the two can coexist."
    ),

    "Pseudogout": (
        "Arthropathy from calcium pyrophosphate dihydrate crystal "
        "deposition, formerly pseudogout. "
        "Epidemiology: strongly age-related, uncommon under 60. "
        "Clinical features: acute severe pain with overlying erythema, "
        "reduced range of movement, swelling and warmth. "
        "Differential: distinguished from acute gout by the joints involved "
        "- knee and wrist rather than first MTP - a longer duration of "
        "attacks, and more frequent systemic symptoms. "
        "Ix: aspiration shows positively birefringent rhomboid crystals, the "
        "mirror image of gout; chondrocalcinosis on X-ray is common with age "
        "and not diagnostic alone. "
        "Mx: NSAIDs, colchicine or intra-articular steroid. No equivalent of "
        "urate-lowering therapy exists. "
        "Note: look for a secondary cause if young or polyarticular - check "
        "ferritin, calcium, PTH and magnesium for haemochromatosis, "
        "hyperparathyroidism and hypomagnesaemia."
    ),

    "Fibromyalgia": (
        "Chronic widespread pain with fatigue, unrefreshing sleep and "
        "cognitive difficulty, understood as central sensitisation rather "
        "than tissue damage. "
        "Epidemiology: women > men; often coexists with mood disorders and "
        "irritable bowel syndrome. "
        "Clinical features: widespread pain over 3 months, fatigue, "
        "non-restorative sleep, cognitive fog, hypersensitivity to touch and "
        "sound. "
        "Ix: inflammatory markers, CK and imaging are all normal - and that "
        "normality is the finding. Investigate only what the history "
        "suggests; repeated negative testing entrenches illness beliefs. "
        "Mx: graded patient-led exercise has the best evidence, with sleep "
        "measures, CBT and pain education; amitriptyline or duloxetine may "
        "help; opioids do not and cause harm. "
        "Note: coexists with inflammatory disease often enough that finding "
        "one does not exclude the other."
    ),


    # ═══════════ TOPIC 1: CARDIOVASCULAR AND RESPIRATORY ════════════════

    "Heart failure": (
        "Clinical syndrome in which cardiac output is inadequate for tissue "
        "demand, or is achieved only at raised filling pressures. "
        "Classification: HFrEF 40% or below; HFmrEF 41-49%; HFpEF 50% or "
        "above. Only HFrEF has therapy that reliably improves mortality. "
        "Causes: ischaemic heart disease and hypertension dominate; valvular "
        "disease; arrhythmia; alcohol; chemotherapy; cardiomyopathy. "
        "Clinical features: exertional dyspnoea and orthopnoea; raised JVP; "
        "displaced apex with a third heart sound; bibasal crackles; "
        "peripheral oedema. "
        "Ix: BNP or NT-proBNP - a normal level essentially excludes it; a "
        "normal ECG makes HFrEF unlikely; echocardiography gives the "
        "phenotype; UEC, TFT, iron studies. "
        "Mx: HFrEF gets the four pillars - ARNI or ACE inhibitor; "
        "beta-blocker; mineralocorticoid receptor antagonist; SGLT2 "
        "inhibitor - started early at low dose and uptitrated, since each "
        "independently reduces mortality. Diuretics relieve congestion "
        "without changing survival. In HFpEF, an SGLT2 inhibitor. "
        "Note: correct iron deficiency even without anaemia - IV iron improves "
        "symptoms and admissions in HFrEF. ""Red flags: hypotension with cool peripheries and oliguria means "
        "cardiogenic shock."
    ),

    "Myocardial infarction": (
        "Spectrum of myocardial ischaemia from unstable plaque: unstable "
        "angina, NSTEMI, STEMI. "
        "Pathophysiology: plaque rupture with superimposed thrombus. Complete "
        "occlusion gives ST elevation; partial occlusion gives NSTEMI or "
        "unstable angina. "
        "Clinical features: central crushing chest pain radiating to jaw or "
        "arm; sweating, nausea, dyspnoea. Frequently atypical in women, older "
        "people and diabetes - dyspnoea or collapse without chest pain. "
        "Ix: ECG within 10 minutes, repeated if pain continues; "
        "high-sensitivity troponin at 0 and 1-3 hours, where the change "
        "matters more than a single value. "
        "Mx: aspirin 300 mg immediately, a second antiplatelet, "
        "anticoagulation and glyceryl trinitrate. STEMI needs reperfusion - "
        "primary PCI within 90 minutes, or thrombolysis if PCI is not "
        "achievable within 120, the usual constraint outside metro Australia. "
        "NSTEMI is risk-stratified with GRACE. "
        "Secondary prevention: dual antiplatelet therapy; statin; ACE "
        "inhibitor; beta-blocker; cardiac rehabilitation. "
        "Note: a normal troponin does not exclude unstable angina; posterior "
        "STEMI shows ST depression in V1-V3. "
        "Red flags: new murmur, hypotension or pulmonary oedema suggests "
        "mechanical complication."
    ),

    "Atrial fibrillation": (
        "Supraventricular arrhythmia with disorganised atrial activity and an "
        "irregularly irregular ventricular response. "
        "Causes: hypertension; ischaemic and valvular heart disease; "
        "thyrotoxicosis; alcohol; sepsis; obstructive sleep apnoea. "
        "Clinical features: palpitations, dyspnoea, fatigue or syncope - or "
        "asymptomatic and found incidentally, which is common. "
        "Ix: ECG shows absent P waves, irregularly irregular; TFT, UEC; "
        "echocardiography; Holter if paroxysmal. "
        "Mx: three separate decisions. Rate control with a beta-blocker or "
        "diltiazem suits most; rhythm control - flecainide, amiodarone or "
        "cardioversion - where symptoms persist or the AF is new. "
        "Anticoagulation is decided independently of rate or rhythm, on "
        "CHA2DS2-VASc against HAS-BLED, DOAC preferred except in moderate to "
        "severe mitral stenosis or a mechanical valve. "
        "Note: anticoagulation decisions do not change once sinus rhythm is "
        "restored - stroke risk tracks the underlying substrate, not the "
        "rhythm on the day. "
        "Red flags: instability means immediate synchronised cardioversion. A "
        "very rapid, broad, irregular complex suggests pre-excited AF in WPW "
        "- avoid AV nodal blockers, which can precipitate VF."
    ),

    "COPD": (
        "Progressive airflow limitation that is not fully reversible, from "
        "chronic bronchitis and emphysema. "
        "Causes: smoking overwhelmingly; biomass exposure; occupational dust; "
        "alpha-1 antitrypsin deficiency if young or basal-predominant. "
        "Clinical features: chronic dyspnoea; productive cough and wheeze; "
        "recurrent infection; hyperinflation. Clubbing is not a feature and "
        "should prompt a search for cancer or bronchiectasis. "
        "Ix: post-bronchodilator spirometry showing FEV1/FVC below 0.7 is "
        "required for diagnosis; chest X-ray; alpha-1 antitrypsin if "
        "indicated. "
        "Mx: smoking cessation is the only intervention that alters "
        "progression. Pulmonary rehabilitation and vaccination; inhaled "
        "therapy stepped from a reliever through LAMA or LABA to dual "
        "therapy, adding an inhaled corticosteroid if exacerbations persist "
        "or eosinophils are raised. Long-term oxygen only for chronic "
        "hypoxaemia. "
        "Note: check inhaler technique before escalating - poor technique is "
        "commoner than genuine treatment failure. Target saturations of "
        "88-92% in exacerbation, since over-oxygenation worsens hypercapnia. "
        "Red flags: rising CO2 with acidosis needs non-invasive ventilation."
    ),

    "Asthma": (
        "Chronic inflammatory airway disease with variable, largely "
        "reversible airflow obstruction and airway hyperresponsiveness. "
        "Clinical features: episodic wheeze, cough, chest tightness and "
        "dyspnoea, worse at night and provoked by exercise, cold air, "
        "allergens or infection. Variability is the diagnostic hallmark. "
        "Ix: spirometry with bronchodilator reversibility - FEV1 rise of 12% "
        "and 200 mL; peak flow variability. Normal spirometry between "
        "episodes does not exclude asthma. "
        "Mx: Australian practice has moved away from short-acting beta agonist "
        "monotherapy - adults and adolescents use budesonide-formoterol as "
        "anti-inflammatory reliever, as needed or as maintenance-and-reliever "
        "therapy. Add LAMA or a biologic in severe disease. Written action "
        "plan for everyone. "
        "Note: high short-acting reliever use - more than about three "
        "canisters a year - independently predicts exacerbation and death, "
        "and is the single most useful thing to ask about. "
        "Red flags: a silent chest, exhaustion, cyanosis, or a normalising "
        "CO2 in acute severe asthma all indicate life-threatening disease - "
        "the rising CO2 means the patient is tiring, not improving."
    ),

    "Pulmonary embolism": (
        "Occlusion of pulmonary arteries by thrombus, usually embolised from "
        "a deep vein thrombosis of the lower limb or pelvis. "
        "Clinical features: dyspnoea and pleuritic chest pain, tachycardia, "
        "tachypnoea, hypoxaemia; haemoptysis, syncope, or signs of DVT. "
        "Presentation is frequently non-specific, which is why a structured "
        "probability assessment matters more than clinical impression. "
        "Ix: apply Wells or revised Geneva first. Low probability with a "
        "negative D-dimer excludes PE; otherwise CT pulmonary angiography, or "
        "V/Q in pregnancy or renal impairment. ECG usually shows sinus "
        "tachycardia, S1Q3T3 being uncommon. "
        "Mx: anticoagulate on suspicion where imaging is delayed. A DOAC is "
        "first-line; low molecular weight heparin in pregnancy and cancer. "
        "Thrombolysis for massive PE. Duration 3 months if provoked, longer "
        "if unprovoked or recurrent. "
        "Note: D-dimer is useful only to rule out, and only when pretest "
        "probability is low - ordering it in a high-probability patient "
        "cannot change management and delays imaging. "
        "Red flags: hypotension or arrest means massive PE - consider "
        "immediate thrombolysis."
    ),

    "Pneumonia": (
        "Acute lower respiratory tract infection acquired outside hospital, "
        "with consolidation on imaging. "
        "Causes: Streptococcus pneumoniae most commonly; Haemophilus "
        "influenzae; Mycoplasma; Legionella; respiratory viruses. "
        "Clinical features: fever, productive cough, pleuritic pain, "
        "dyspnoea; bronchial breathing, focal crackles, dullness to "
        "percussion. Older patients may present only with confusion or a "
        "fall. "
        "Ix: chest X-ray; FBC, UEC, CRP; blood and sputum cultures if moderate "
        "to severe. Severity is scored with CORB or SMART-COP in Australia "
        "rather than CURB-65. "
        "Mx: per eTG - amoxicillin for mild disease, adding doxycycline for "
        "atypical cover; IV benzylpenicillin with doxycycline for moderate; "
        "ceftriaxone with azithromycin for severe. Review at 48 hours. "
        "Note: tropical northern Australia is the exception that changes "
        "management - Burkholderia pseudomallei (melioidosis) and Acinetobacter "
        "require meropenem-based cover in severe disease, so ask about "
        "location and wet-season exposure. "
        "Red flags: failure to improve by 48-72 hours suggests empyema, "
        "abscess, resistant organism or an obstructing lesion."
    ),

    "Hypertension": (
        "Persistently raised arterial pressure - in Australia, clinic readings "
        "of 140/90 mmHg or above on repeated occasions. "
        "Causes: primary in about 90%; renal parenchymal and renovascular "
        "disease; primary aldosteronism; phaeochromocytoma; Cushing "
        "syndrome; coarctation; obstructive sleep apnoea; NSAIDs and the "
        "COCP. Almost always asymptomatic - detection is by measurement. "
        "Ix: confirm with ambulatory or home monitoring. Assess end-organ "
        "damage - UEC, urine ACR, fundoscopy, ECG - and calculate absolute "
        "cardiovascular risk, since Australian thresholds follow that risk "
        "rather than the pressure alone. "
        "Mx: lifestyle for all. First-line agents are an ACE inhibitor or ARB, "
        "a dihydropyridine calcium channel blocker, or a thiazide-like "
        "diuretic; low-dose combination beats maximising one agent. "
        "Note: investigate for a secondary cause when hypertension resists "
        "three agents, presents before 30, or comes with hypokalaemia. "
        "Primary aldosteronism is commoner than traditionally taught and is "
        "potentially curable. "
        "Red flags: BP above 180/110 with end-organ damage is a hypertensive "
        "emergency needing controlled intravenous reduction - dropping it too "
        "fast causes watershed infarction."
    ),

    # ══════════════════ TOPIC 4: DERMATOLOGY ════════════════════════════

    "Erythema nodosum": (
        "Septal panniculitis presenting as tender erythematous nodules on "
        "the anterior shins - the commonest reactive panniculitis. "
        "Clinical features: tender poorly demarcated nodules 1-10 cm, "
        "bilateral, evolving from red to bruise-like and resolving over 2-8 "
        "weeks. They never ulcerate or scar, which distinguishes them from "
        "nodular vasculitis. "
        "Causes: streptococcal pharyngitis (commonest); sarcoidosis - Lofgren "
        "syndrome with hilar adenopathy, arthritis and fever has a good "
        "prognosis; tuberculosis; IBD; pregnancy and the COCP; Behcet "
        "disease. About half are idiopathic. "
        "Ix: clinical; biopsy only if atypical. Seek the cause with ASOT, "
        "chest X-ray, ACE and TSH. "
        "Mx: treat the cause; NSAIDs, rest and elevation; potassium iodide "
        "if refractory. "
        "Note: chest X-ray in essentially everyone - sarcoidosis and "
        "tuberculosis both present this way and are otherwise missed."
    ),

    "Acne vulgaris": (
        "Chronic inflammatory disease of the pilosebaceous unit with "
        "comedones, papules, pustules and, when severe, nodules and cysts. "
        "Epidemiology: begins in early puberty, settling through the 20s-30s. "
        "Pathophysiology: androgen-driven sebum, follicular "
        "hyperkeratinisation forming the comedone, C. acnes colonisation, "
        "then inflammation - each first-line agent hits a different step, "
        "which is why combinations beat monotherapy. "
        "Clinical features: face, chest, upper back. Mild is comedonal; "
        "moderate adds papules and pustules; severe has nodules and scarring. "
        "Mx: mild - topical benzoyl peroxide and/or a retinoid (adapalene, "
        "tretinoin). Moderate - add oral doxycycline, or the COCP in women. "
        "Severe - oral isotretinoin via dermatology. "
        "Note: never use an antibiotic without benzoyl peroxide or a "
        "retinoid alongside - monotherapy breeds resistance and eTG advises "
        "against it. Isotretinoin is highly teratogenic."
    ),

    "Psoriasis": (
        "Chronic immune-mediated disease of accelerated keratinocyte "
        "turnover producing well-demarcated scaly plaques. "
        "Epidemiology: bimodal onset in the 20s and 50s; strongly genetic. "
        "Pathophysiology: an IL-23/Th17 axis shortens epidermal transit from "
        "about a month to days, giving parakeratosis and thick silvery "
        "scale. "
        "Clinical features: plaques on extensor surfaces, scalp and sacrum; "
        "Auspitz and Koebner signs; nail pitting. Variants: guttate, "
        "flexural, pustular, erythrodermic. "
        "Associations: psoriatic arthritis in up to 30%; metabolic syndrome, "
        "cardiovascular disease. "
        "Mx: topical corticosteroid with calcipotriol; phototherapy if "
        "extensive; methotrexate or acitretin; biologics per PBS. "
        "Note: ask about joints at every review - psoriatic arthritis is "
        "erosive and skin usually precedes it by years. Avoid systemic "
        "steroids, which risk pustular rebound on withdrawal."
    ),

    "Eczema": (
        "Chronic relapsing pruritic inflammatory skin disease, the "
        "commonest eczema and part of the atopic triad. "
        "Epidemiology: begins in infancy; most improve by adolescence. "
        "Pathophysiology: barrier dysfunction first - filaggrin "
        "loss-of-function is the strongest genetic risk - allowing allergen "
        "entry and Th2 inflammation. That order is why emollients are "
        "treatment, not adjunct. "
        "Clinical features: itch is obligatory; facial and extensor in "
        "infants, flexural in older children and adults, with "
        "lichenification and excoriation marking chronicity. "
        "Mx: liberal emollients regardless of activity; topical steroid "
        "matched to site; calcineurin inhibitors for face and flexures. "
        "Note: undertreatment through steroid phobia causes more harm than "
        "appropriate steroid use, and is the commonest reason treatment "
        "fails. Monomorphic punched-out erosions mean eczema herpeticum - "
        "urgent aciclovir."
    ),

    "Cellulitis": (
        "Acute bacterial infection of deep dermis and subcutaneous tissue, "
        "usually Streptococcus pyogenes then Staphylococcus aureus. "
        "Clinical features: spreading erythema, warmth, swelling and "
        "tenderness with poorly demarcated borders, usually one lower limb, "
        "often with fever and an entry point such as tinea pedis. "
        "Differential: bilateral presentation is almost never cellulitis - "
        "consider venous eczema, lipodermatosclerosis, chronic oedema, DVT. "
        "Ix: clinical. Blood cultures only if systemically unwell; mark the "
        "erythema border to track progress. "
        "Mx: oral flucloxacillin or cefalexin; IV if systemically unwell. "
        "Elevate the limb and treat the entry point to reduce recurrence. "
        "Note: erythema often appears to extend in the first 24-48 h despite "
        "effective treatment, so that alone is not a reason to switch. "
        "Red flags: pain out of proportion, crepitus, bullae or necrosis "
        "suggest necrotising fasciitis - a surgical emergency."
    ),

    "Urticaria": (
        "Transient pruritic wheals from mast cell degranulation, with or "
        "without angioedema. "
        "Clinical features: individual wheals resolve within 24 h leaving no "
        "mark, though the eruption may persist far longer. Acute is under 6 "
        "weeks, chronic beyond. "
        "Causes: acute - viral infection (commonest), drugs, food, stings. "
        "Chronic spontaneous urticaria is usually autoimmune. "
        "Ix: none in typical acute disease; FBC and ESR/CRP if chronic. "
        "Extensive allergy testing has poor yield. "
        "Mx: a second-generation antihistamine (cetirizine, fexofenadine), "
        "up-titrated to four times standard dose if needed; omalizumab if "
        "refractory. "
        "Note: a single lesion lasting beyond 24 h, or leaving bruising, is "
        "urticarial vasculitis and needs biopsy. "
        "Red flags: wheals with airway or GI symptoms or hypotension are "
        "anaphylaxis - IM adrenaline, not an antihistamine."
    ),

    # ── Batch 1 ───────────────────────────────────────────────
    # Chosen by deck frequency, not by height: queried against the
    # live collection over AnkiConnect and kept only the over-cap
    # conditions that actually appear on cards. The tallest entries
    # in the database - Fournier gangrene, Tularaemia, Pellagra,
    # McArdle disease - returned zero notes, so ordering by height
    # would have spent the batch on conditions never looked up.
    "Vasculitis":
        "Inflammation of blood vessel walls, classified by the size of "
        "vessel predominantly involved. Classification: large vessel - "
        "giant cell arteritis, Takayasu arteritis; medium vessel - "
        "polyarteritis nodosa, Kawasaki disease; small vessel "
        "ANCA-associated - granulomatosis with polyangiitis, microscopic "
        "polyangiitis, eosinophilic granulomatosis with polyangiitis; small "
        "vessel immune complex - IgA vasculitis, cryoglobulinaemic, "
        "anti-GBM. Clinical features: constitutional illness with "
        "multi-organ involvement - palpable purpura, glomerulonephritis, "
        "alveolar haemorrhage, mononeuritis multiplex, and sinusitis with "
        "saddle-nose deformity in GPA. Ix: ANCA with PR3 specificity in GPA "
        "and MPO in MPA and EGPA; anti-GBM, complement, cryoglobulins; "
        "urinalysis for red cell casts; biopsy of the affected organ "
        "confirms. Mx: induction with rituximab or cyclophosphamide plus "
        "high-dose prednisolone; maintenance with rituximab or "
        "azathioprine; plasma exchange for anti-GBM disease or severe "
        "alveolar haemorrhage. Note: the emergency is a rising creatinine "
        "with an active sediment, not the rash.",
    "Pleural effusion":
        "Fluid in the pleural space, separated into transudate and exudate "
        "by Light criteria. Criteria: exudate if pleural to serum protein "
        "exceeds 0.5, pleural to serum LDH exceeds 0.6, or pleural LDH "
        "exceeds two thirds the upper limit of normal serum LDH. Causes: "
        "transudate - heart failure, cirrhosis, nephrotic syndrome, "
        "hypothyroidism; exudate - parapneumonic, malignancy, tuberculosis, "
        "pulmonary embolism, connective tissue disease, oesophageal "
        "rupture. Sx: dyspnoea and pleuritic pain, with a stony dull "
        "percussion note, reduced breath sounds and reduced vocal resonance "
        "at the base. Ix: erect chest radiograph blunts the costophrenic "
        "angle beyond about 200 mL; ultrasound-guided aspiration for "
        "protein, LDH, glucose, pH, cytology, MCS and adenosine deaminase. "
        "Mx: treat the cause; intercostal drain for a complicated "
        "parapneumonic effusion or empyema; indwelling pleural catheter or "
        "talc pleurodesis for recurrent malignant effusion. Note: pleural "
        "pH below 7.2 in a parapneumonic effusion means it needs drainage, "
        "not more antibiotics.",
    "Acute liver failure":
        "Coagulopathy with encephalopathy developing within 26 weeks in "
        "someone without pre-existing liver disease. Causes: paracetamol is "
        "the commonest in Australia; also hepatitis A and E, idiosyncratic "
        "drug reaction, Wilson disease, Budd-Chiari syndrome, ischaemic "
        "hepatitis, acute fatty liver of pregnancy. Clinical features: "
        "jaundice preceding encephalopathy graded I to IV, asterixis "
        "progressing to coma; cerebral oedema in grade III to IV is the "
        "leading cause of death. Ix: INR and lactate track severity; "
        "paracetamol concentration, viral serology, caeruloplasmin, hepatic "
        "vein Doppler; watch glucose, creatinine and cultures for the usual "
        "complications. Mx: intensive care; acetylcysteine, which benefits "
        "non-paracetamol causes as well; glucose and electrolyte support; "
        "early referral to a transplant unit against King's College "
        "criteria; avoid sedation. Note: INR is the prognostic marker here, "
        "so correcting it without active bleeding discards the best measure "
        "of trajectory.",
    "Septic arthritis":
        "Bacterial infection of a joint. Cartilage is destroyed within "
        "days, so this is a same-day emergency. Causes: Staphylococcus "
        "aureus most often; streptococci; Neisseria gonorrhoeae in young "
        "sexually active adults; Gram-negative bacilli in the elderly and "
        "immunosuppressed. Risk factors: prosthetic joint, rheumatoid "
        "arthritis, diabetes, injecting drug use, immunosuppression, "
        "overlying skin infection. Sx: a single hot swollen joint, severe "
        "pain on any movement, inability to weight-bear, fever. Ix: urgent "
        "joint aspiration before antibiotics for synovial white cell count, "
        "Gram stain, culture and crystal microscopy; blood cultures; CRP. "
        "Mx: flucloxacillin intravenously as empirical cover per eTG, "
        "vancomycin where MRSA is likely, ceftriaxone for gonococcal "
        "disease; joint washout or repeated aspiration alongside. Note: a "
        "synovial white cell count under 50 x 10^9/L does not exclude it, "
        "particularly in a prosthetic joint, and crystals do not exclude it "
        "either.",
    "Colorectal cancer":
        "Adenocarcinoma of the colon or rectum, and the second commonest "
        "cause of cancer death in Australia. Screening: the National Bowel "
        "Cancer Screening Program offers immunochemical faecal occult blood "
        "testing every two years from 45 to 74, with colonoscopy for a "
        "positive result. Causes: adenoma-carcinoma sequence through APC, "
        "KRAS and TP53; mismatch repair deficiency in Lynch syndrome; the "
        "serrated pathway through BRAF. Risk factors: inflammatory bowel "
        "disease, family history, processed meat, obesity, alcohol, "
        "smoking. Sx: right-sided disease gives iron deficiency anaemia and "
        "a mass; left-sided gives altered bowel habit, rectal bleeding, "
        "tenesmus and obstruction. Ix: colonoscopy with biopsy; staging CT "
        "of chest, abdomen and pelvis; MRI rectum for local staging and "
        "circumferential margin. Mx: resection; neoadjuvant "
        "chemoradiotherapy for locally advanced rectal disease; adjuvant "
        "oxaliplatin-based chemotherapy for stage III per eviQ.",
    "Anorexia nervosa":
        "Restriction of intake relative to requirements, with intense fear "
        "of weight gain and disturbed experience of body weight or shape. "
        "Epidemiology: onset usually in adolescence with female "
        "predominance; the highest mortality of any psychiatric disorder, "
        "from medical complications and from suicide. Complications: "
        "bradycardia, hypotension, hypothermia, prolonged QT, hypokalaemia, "
        "hypophosphataemia, amenorrhoea, reduced bone mineral density, "
        "dental erosion where there is purging. Ix: ECG, electrolytes, "
        "phosphate, magnesium, glucose, liver function, bone densitometry. "
        "Mx: medical stabilisation first, with thiamine before nutrition "
        "and daily phosphate, potassium and magnesium as intake increases; "
        "psychological therapy is definitive - CBT-E, MANTRA or specialist "
        "supportive clinical management in adults, family-based treatment "
        "in adolescents. Antidepressants do not restore weight. Australian "
        "notes: an Eating Disorder Plan funds extended psychological and "
        "dietetic sessions under Medicare. Note: DSM-5-TR sets no BMI "
        "threshold for diagnosis; BMI grades severity only.",
    "Peptic ulcer disease":
        "Mucosal break extending through the muscularis mucosae of the "
        "stomach or duodenum. Causes: Helicobacter pylori and NSAIDs "
        "account for nearly all of it, the latter by suppressing mucosal "
        "prostaglandins; gastrinoma is rare. Sx: epigastric burning pain. "
        "Duodenal ulcer eases with food and wakes the patient at night; "
        "gastric ulcer is provoked by eating and comes with weight loss. "
        "Complications: bleeding with haematemesis or melaena, perforation, "
        "gastric outlet obstruction, penetration into the pancreas. Ix: "
        "gastroscopy is definitive and every gastric ulcer is biopsied to "
        "exclude malignancy; urea breath test or faecal antigen for H. "
        "pylori, off proton pump inhibitor for two weeks. Mx: eradication "
        "where H. pylori is present, esomeprazole with amoxycillin and "
        "clarithromycin for seven days per eTG; stop the NSAID; endoscopic "
        "haemostasis for bleeding; surgery for perforation. Note: serology "
        "cannot separate current from past infection and must not be used "
        "to confirm eradication.",
    "Hypokalaemia":
        "Serum potassium below 3.5 mmol/L; below 2.5 mmol/L is "
        "life-threatening. Causes: renal loss through diuretics, "
        "hyperaldosteronism, Cushing syndrome or renal tubular acidosis; "
        "gastrointestinal loss through vomiting or diarrhoea; shift into "
        "cells with insulin, beta-2 agonists or alkalosis. Sx: weakness, "
        "cramps, ileus, polyuria and palpitations, with rhabdomyolysis when "
        "severe. Ix: ECG shows T-wave flattening, U waves, ST depression "
        "and a long QU interval; check magnesium, bicarbonate and urinary "
        "potassium. Mx: oral potassium chloride if mild; intravenous "
        "potassium chloride for severe or symptomatic hypokalaemia, no "
        "faster than 10 mmol/hour peripherally and faster only with central "
        "access and cardiac monitoring; replace magnesium alongside. Note: "
        "potassium will not correct while magnesium is low, because "
        "magnesium depletion disinhibits the ROMK channel and drives renal "
        "potassium wasting.",
    "Aortic dissection":
        "Intimal tear allowing blood into the aortic media and creating a "
        "false lumen. Classification: Stanford A involves the ascending "
        "aorta and is surgical; Stanford B is confined distal to the left "
        "subclavian artery. Risk factors: hypertension above all, bicuspid "
        "aortic valve, Marfan and Ehlers-Danlos syndromes, Turner syndrome, "
        "coarctation, cocaine, third trimester pregnancy. Sx: abrupt "
        "tearing chest or interscapular pain, maximal at onset; blood "
        "pressure differential over 20 mmHg between arms; new aortic "
        "regurgitation; stroke, paraplegia or limb ischaemia from branch "
        "vessel occlusion. Ix: CT aortography; transoesophageal "
        "echocardiography if too unstable to move. A normal chest "
        "radiograph excludes nothing. Mx: rate control before pressure "
        "control - intravenous esmolol or labetalol to a heart rate under "
        "60, then a vasodilator to systolic 100 to 120 mmHg. Type A goes to "
        "theatre immediately; uncomplicated type B is medical; complicated "
        "type B gets endovascular repair.",
    "Rhabdomyolysis":
        "Skeletal muscle breakdown releasing myoglobin, potassium, "
        "phosphate and creatine kinase into the circulation. Causes: crush "
        "injury, a long lie after a fall, seizures, extreme exertion, "
        "statins, alcohol, psychostimulants, heat stroke, neuroleptic "
        "malignant syndrome. Sx: myalgia, weakness and dark cola-coloured "
        "urine, though the full triad appears in a minority. Ix: creatine "
        "kinase above five times the upper limit confirms it; urine "
        "dipstick positive for blood with no red cells on microscopy; "
        "follow potassium, phosphate, calcium, urate and creatinine. Mx: "
        "early high-volume 0.9% sodium chloride titrated to urine output "
        "above 1 to 2 mL/kg/hour; treat hyperkalaemia; dialysis for "
        "refractory acidosis, hyperkalaemia or oliguric acute kidney "
        "injury. Note: early hypocalcaemia reflects calcium deposition in "
        "damaged muscle and rebounds during recovery, so leave it alone "
        "unless symptomatic.",
    "Infective endocarditis":
        "Infection of the endocardium, usually a valve, and usually one "
        "already abnormal - prosthetic, rheumatic, congenital, previously "
        "infected - or in the setting of injecting drug use or an "
        "intracardiac device. Causes: Staphylococcus aureus commonest "
        "overall and in injecting drug use; viridans streptococci after "
        "oral bacteraemia; coagulase-negative staphylococci on prosthetic "
        "valves; enterococci, HACEK organisms and Coxiella burnetii make up "
        "most of the rest. Sx: fever with a new murmur, embolic stroke, or "
        "heart failure from acute regurgitation; peripheral stigmata are "
        "uncommon but specific. Ix: three sets of blood cultures before "
        "antibiotics, then echocardiography, transoesophageal if the "
        "transthoracic is unrevealing; modified Duke criteria. Mx: "
        "prolonged intravenous antibiotics directed at the organism, "
        "empirically flucloxacillin with benzylpenicillin and gentamicin "
        "per eTG; surgery for heart failure, uncontrolled infection, "
        "abscess or a large mobile vegetation. Note: rheumatic heart "
        "disease remains a major substrate in Aboriginal and Torres Strait "
        "Islander communities.",
    "Coeliac disease":
        "Immune-mediated enteropathy triggered by gluten in HLA-DQ2 or DQ8 "
        "carriers, causing villous atrophy and malabsorption. Sx: "
        "diarrhoea, steatorrhoea, bloating and weight loss, although the "
        "commonest adult presentation is iron deficiency anaemia with no "
        "bowel symptoms at all. Extraintestinal: dermatitis herpetiformis, "
        "osteoporosis, transaminitis, gluten ataxia, peripheral neuropathy, "
        "hyposplenism. Associations: type 1 diabetes, autoimmune thyroid "
        "disease, selective IgA deficiency, Down syndrome. Ix: anti-tissue "
        "transglutaminase IgA with a total IgA, taken while still eating "
        "gluten; duodenal biopsy showing intraepithelial lymphocytosis, "
        "crypt hyperplasia and villous atrophy confirms it in adults. Mx: "
        "lifelong gluten-free diet with dietitian input; replace iron, "
        "folate, B12, calcium and vitamin D; bone densitometry; "
        "pneumococcal vaccination for hyposplenism. Note: serology "
        "normalises on a gluten-free diet, so anyone already avoiding "
        "gluten needs a formal gluten challenge before testing.",
    "Ankylosing spondylitis":
        "Chronic inflammatory arthritis of the sacroiliac joints and spine, "
        "the radiographic form of axial spondyloarthritis; over 90% carry "
        "HLA-B27. Epidemiology: onset before 45 and usually in the "
        "twenties, with male predominance. Sx: inflammatory back pain with "
        "morning stiffness beyond an hour that eases with movement and "
        "worsens with rest; alternating buttock pain; reduced chest "
        "expansion; enthesitis at the Achilles and plantar fascia. "
        "Extra-articular: acute anterior uveitis, inflammatory bowel "
        "disease, psoriasis, aortic regurgitation, conduction block, apical "
        "pulmonary fibrosis. Ix: MRI of the sacroiliac joints shows bone "
        "marrow oedema years before radiographic sacroiliitis; HLA-B27 and "
        "CRP support the diagnosis without making it. Mx: continuous "
        "exercise and physiotherapy are the mainstay; NSAIDs first-line; a "
        "TNF or IL-17 inhibitor where disease stays active, which on the "
        "PBS requires a BASDAI of 4 or more after an adequate NSAID trial. "
        "Conventional DMARDs do not work for axial disease.",
    "Serotonin syndrome":
        "Excess serotonergic activity, usually from a drug combination, "
        "developing within hours rather than days. Causes: an SSRI or SNRI "
        "with a monoamine oxidase inhibitor is the most dangerous pairing; "
        "also tramadol, pethidine, fentanyl, linezolid, triptans, lithium, "
        "St John's wort, MDMA and cocaine. Sx: neuromuscular excitation "
        "with clonus, hyperreflexia and tremor, greatest in the lower "
        "limbs; autonomic instability with hyperthermia, tachycardia and "
        "diaphoresis; agitation and delirium. Criteria: Hunter criteria "
        "require a serotonergic agent plus spontaneous clonus, or inducible "
        "or ocular clonus with agitation or diaphoresis, or tremor with "
        "hyperreflexia, or hypertonia with temperature above 38.5 C and "
        "clonus. Differential: neuroleptic malignant syndrome evolves over "
        "days with lead-pipe rigidity and hyporeflexia. Mx: stop the "
        "offending drugs; benzodiazepines for agitation and rigidity; "
        "active cooling; oral cyproheptadine; intubation and paralysis if "
        "hyperthermia is uncontrolled.",
}


# Fill the new entries' summaries from the table above, so the text is
# written once and a mismatch between the two is impossible.
for _nc in NEW_CONDITIONS:
    _nc["summary"] = RICH_SUMMARIES.get(_nc["name"], "")
